services:
  # --- Define the Web Service first ---


  # --- Define the Cron Job as a separate service ---
  - type: cron
    name: nudge-scheduler # Give the cron service a name
    runtime: node # Runtime env for the cron runner itself (doesn't impact curl)
    schedule: "*/2 * * * *" # Your desired schedule
    # buildCommand: 'echo "No build needed for curl command"' # Often not needed
    startCommand: curl -sf ${RENDER_EXTERNAL_URL}/api/cron/nudge # The command to execute
    # Note: RENDER_EXTERNAL_URL here should automatically reference the primary 
    # web service ('scheduler-agent-prod') defined within the same blueprint.
    # No explicit envVar needed for it typically.