# Define the primary web service that runs the Next.js app and API
services:
  - type: web
    name: scheduler-agent-prod # Ensure this name is unique in your Render account
    runtime: node # Or your specific node version if needed, e.g., node:18
    buildCommand: npm install && npm run build # Or your specific build command
    startCommand: npm start # Or your specific start command
    envVars:
      - key: NODE_ENV
        value: production
      # --- ADD ALL YOUR OTHER REQUIRED ENV VARS HERE ---
      - key: SUPABASE_URL
        fromSecret: true # Example: if stored as Render secret
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromSecret: true # Example: if stored as Render secret
      - key: POSTMARK_SERVER_TOKEN
        fromSecret: true # Example: if stored as Render secret
      - key: POSTMARK_SENDER_ADDRESS
        value: amy@yourdomain.com # Replace with your actual sender address
      - key: OPENAI_API_KEY
        fromSecret: true # Example: if stored as Render secret
      - key: LANGFUSE_SECRET_KEY
        fromSecret: true # Example: if stored as Render secret
      - key: LANGFUSE_PUBLIC_KEY
        fromSecret: true # Example: if stored as Render secret
      - key: LANGFUSE_BASEURL
        value: https://cloud.langfuse.com # Or your correct URL (NO QUOTES)
      # Add any others your application needs

# Define the scheduled task using the top-level 'cron:' key
cron:
  - job: nudgeParticipants # Name for the job
    schedule: "*/2 * * * *" # Your desired schedule (e.g., every 2 mins for testing)
    # This command hits the nudge endpoint on the web service defined above
    command: curl -sf ${RENDER_EXTERNAL_URL}/api/cron/nudge